package AddNaming;


/**
* AddNaming/Add.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Saturday, February 18, 2017 3:09:26 PM GMT
*/

public interface Add extends AddOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Add
