package AddNaming;

/**
* AddNaming/AddHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Add.idl
* Saturday, February 18, 2017 3:09:26 PM GMT
*/

public final class AddHolder implements org.omg.CORBA.portable.Streamable
{
  public AddNaming.Add value = null;

  public AddHolder ()
  {
  }

  public AddHolder (AddNaming.Add initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddNaming.AddHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddNaming.AddHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddNaming.AddHelper.type ();
  }

}
